language: python
sudo: true
python:
  - "2.7"
  # - "3.4"

# command to install dependencies
# some are only used for travis/coveralls so we are installing them here only
install:
  - ./test/setup_test.sh

# command to run tests
script:
  # so to help eventual debug: knowing what exact versions are in use can be rather useful.
  - pip freeze
  # Code static analysis
  - pep8 --max-line-length=100 --exclude='*.pyc, *.cfg, *.log' --ignore='E402' alignak_module_external_commands/*
  - pylint --rcfile=.pylintrc alignak_module_external_commands/
  # Code dynamic analysis
  - cd test
  - nosetests -xv --process-restartworker test_module.py
  - cd ..
